### ISSUE TITLE
url not found, cannot install via pip

### ISSUE THREAD

**Issue by JakobHuesken** [MkLHX/Raspberry_Pi_Master_for_ESP32_I2C_SLAVE#1]
Hello, I can't install your module via pip install raspberrypi-esp32-i2c on my raspberrypi. It says that the url: https://pypi.org/simple/raspberrypi-esp32-i2c/ cannot be found.
`pip install raspberrypi-esp32-i2c
collecting raspberrypi-esp32-i2c
Exception
Traceback (most recent call last):
   File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
      status = self.run(options, args)
   File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 353, in run
      wb.build(autobuilding=True)
   File "/usr/lib/python3/dist-packages/pip/wheel.py", line 749, in build
      self.requirement_set.prepare_files(self-finder)
   File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 380, in prepare_files
      ignore_dependencies=self.ignore_dependencies))
   File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 554, in _prepare_files
      require_hashes
    File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 278, in populate_link
      self.link = finder.find_requirement(self, upgrade)
   File "/usr/lib/python3/dist-packages/pip/index.py", line 465, in find_requirement
      all_candidates = self.find_all_candidates(req.name)
   File "/usr/lib/python3/dist-packages/pip/index.py", line 423, in find_all_candidates
      for page in self._get_pages(url_locations, project_name):
   File "/usr/lib/python3/dist-packages/pip/index.py", line 568, in _get_pages
      page = self._get.page(location)
   File "/usr/lib/python3/dist-packages/pip/index.py", line 683, in _get_page
      return HTMLPage.get_page(link, session=self.session)
   File "/usr/lib/python3/dist-packages/pip/index.py", line 795, in get_page
      resp.raise_for_status()
   File "/usr/share/python-wheels/requests-2.19.4-py2.py3-none-any.whl/requests/models.py", line 935, in raise_for_status
requests-exceptions.HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/raspberrypi-esp32-i2c/`

**Comment by MkLHX** [comment]
Hi @JakobHuesken it's because i never push it on pypi.

Did you need it?

**Comment by JakobHuesken** [comment]
I would like to use your library, so if you could do that, it would be nice. 
Or can I install it via another Method?

**Comment by MkLHX** [comment]
ok! i've just push v0.0.2 on pypi.org 
https://pypi.org/manage/project/raspberrypi-esp32-i2c/release/0.0.2/

**Comment by JakobHuesken** [comment]
Thank you!

**Comment by MkLHX** [comment]
Great! please put a like star on this repo ;-)

**Comment by adnan6336** [comment]
The above pypi link is not working. please help!
Thanks for your contribution :)

**Comment by MkLHX** [comment]
hi @adnan6336 

do you see the releases menu
https://github.com/MkLHX/Raspberry_Pi_Master_for_ESP32_I2C_SLAVE/releases/tag/0.0.6

and the pypi repo is here https://pypi.org/project/raspberrypi-esp32-i2c/


so like i said on the reamde.md you can install it by using 

pip install raspberrypi-esp32-i2c

**Comment by adnan6336** [comment]
Yeah thanks for that. 
That "pip install raspberrypi-esp32-i2c" doesn't work for me but when I run 
"pip3 install raspberrypi-esp32-i2c"
It runs perfectly. 
thanks again
